[project]
name = "demo-python-devops"
version = "0.1.0"
description = "学习DevOps"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
]

